# Generated by Django 5.1.1 on 2025-05-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('accidents_history', models.TextField(blank=True, null=True)),
                ('ownership_documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('block_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('sold', 'Sold')], default='available', max_length=20)),
            ],
        ),
    ]
