# Generated by Django 5.2.11 on 2026-02-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0002_vehicle1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('buyer_id', models.IntegerField()),
                ('buyer_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hash_code', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
