# Generated by Django 5.2.11 on 2026-02-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
