# Generated by Django 5.2.11 on 2026-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0004_transaction_buyer_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle1',
            name='seller_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
