# Generated by Django 5.1.1 on 2025-05-12 03:49

import seller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellerRegisteredTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[seller.models.validate_name])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('loginid', models.CharField(max_length=30, unique=True)),
                ('mobile', models.CharField(max_length=10, validators=[seller.models.validate_mobile])),
                ('password', models.CharField(max_length=128, validators=[seller.models.validate_password])),
                ('status', models.CharField(default='waiting', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='vehicles/pictures/')),
                ('accidents_history', models.TextField(blank=True)),
                ('ownership_documents', models.FileField(blank=True, null=True, upload_to='vehicles/documents/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_hash', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
