# Generated by Django 5.1.1 on 2025-05-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_vehicle_created_at_remove_vehicle_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
