# Generated by Django 5.2.11 on 2026-02-27 17:46

import seller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_vehicle_purchased_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='purchased_at',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=50, unique=True, validators=[seller.models.validate_vehicle_number]),
        ),
    ]
